wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/ml.py
    python_version: 3.9.6
    cli_version: 0.17.0
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715154744
    t:
      1:
      - 1
      - 5
      - 6
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.6
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
